[project]
name = "tipstream"
description = "A micro-tipping platform built on the Stacks blockchain"
authors = ["Mosas2000"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.tipstream]
path = "contracts/tipstream.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-traits]
path = "contracts/tipstream-traits.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-token]
path = "contracts/tipstream-token.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-escrow]
path = "contracts/tipstream-escrow.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-subscription]
path = "contracts/tipstream-subscription.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-vault]
path = "contracts/tipstream-vault.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-referral]
path = "contracts/tipstream-referral.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-multisig]
path = "contracts/tipstream-multisig.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-rewards]
path = "contracts/tipstream-rewards.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-badges]
path = "contracts/tipstream-badges.clar"
clarity_version = 2
epoch = 3.0

[contracts.tipstream-dao]
path = "contracts/tipstream-dao.clar"
clarity_version = 2
epoch = 3.0

[repl]
costs_version = 3
parser_version = 2

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
